# Generated by Django 4.1.3 on 2025-01-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0002_user_info_delete_trial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='user',
        ),
    ]
