# Generated by Django 4.1.3 on 2025-01-29 10:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Marketing', '0003_remove_user_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
